<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function badcamp19_help($path, $arg) {
    switch ($path) {
        case "admin/help#badcamp19":
            return t("Placeholder"); 
            break; 
    }
}