<?php

function badcamp19_help($path, $arg) {
    switch ($path) {
        case "admin/help#badcamp19":
            return t("Placeholder"); 
            break; 
    }
}

drupal_add_js('https://sdk.amazonaws.com/js/aws-sdk-2.536.0.min.js', array(
    'type' => 'external',
    'requires_jquery' => 'TRUE',
    'scope' => 'header',
));
drupal_add_js('./badcamp19.js', array(
    'type' => 'file',
    'requires_jquery' => 'TRUE',
    'scope' => 'footer',

));